# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{i18n_locale_editor}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Kliment"]
  s.date = %q{2011-03-26}
  s.description = %q{Rails i18n locale web editor as plugin}
  s.email = %q{adam.kliment@virtualmaster.cz}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "CHANGELOG",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/translations_controller.rb",
     "app/helpers/translations_helper.rb",
     "app/models/translation.rb",
     "app/views/layouts/translations.erb",
     "app/views/translations/index.html.erb",
     "config/routes.rb",
     "lib/hash_tools.rb",
     "lib/i18n_locale_editor.rb",
     "lib/translate_monkey_patch.rb",
     "public/i18n_locale_editor/i18n-locale-editor.js",
     "public/i18n_locale_editor/wymeditor/iframe/default/lbl-blockquote.png",
     "public/i18n_locale_editor/wymeditor/iframe/default/lbl-h1.png",
     "public/i18n_locale_editor/wymeditor/iframe/default/lbl-h2.png",
     "public/i18n_locale_editor/wymeditor/iframe/default/lbl-h3.png",
     "public/i18n_locale_editor/wymeditor/iframe/default/lbl-h4.png",
     "public/i18n_locale_editor/wymeditor/iframe/default/lbl-h5.png",
     "public/i18n_locale_editor/wymeditor/iframe/default/lbl-h6.png",
     "public/i18n_locale_editor/wymeditor/iframe/default/lbl-p.png",
     "public/i18n_locale_editor/wymeditor/iframe/default/lbl-pre.png",
     "public/i18n_locale_editor/wymeditor/iframe/default/wymiframe.css",
     "public/i18n_locale_editor/wymeditor/iframe/default/wymiframe.html",
     "public/i18n_locale_editor/wymeditor/jquery.wymeditor.js",
     "public/i18n_locale_editor/wymeditor/jquery.wymeditor.min.js",
     "public/i18n_locale_editor/wymeditor/jquery.wymeditor.pack.js",
     "public/i18n_locale_editor/wymeditor/lang/bg.js",
     "public/i18n_locale_editor/wymeditor/lang/ca.js",
     "public/i18n_locale_editor/wymeditor/lang/cs.js",
     "public/i18n_locale_editor/wymeditor/lang/cy.js",
     "public/i18n_locale_editor/wymeditor/lang/de.js",
     "public/i18n_locale_editor/wymeditor/lang/en.js",
     "public/i18n_locale_editor/wymeditor/lang/es.js",
     "public/i18n_locale_editor/wymeditor/lang/fa.js",
     "public/i18n_locale_editor/wymeditor/lang/fi.js",
     "public/i18n_locale_editor/wymeditor/lang/fr.js",
     "public/i18n_locale_editor/wymeditor/lang/gl.js",
     "public/i18n_locale_editor/wymeditor/lang/he.js",
     "public/i18n_locale_editor/wymeditor/lang/hr.js",
     "public/i18n_locale_editor/wymeditor/lang/hu.js",
     "public/i18n_locale_editor/wymeditor/lang/it.js",
     "public/i18n_locale_editor/wymeditor/lang/nb.js",
     "public/i18n_locale_editor/wymeditor/lang/nl.js",
     "public/i18n_locale_editor/wymeditor/lang/nn.js",
     "public/i18n_locale_editor/wymeditor/lang/pl.js",
     "public/i18n_locale_editor/wymeditor/lang/pt-br.js",
     "public/i18n_locale_editor/wymeditor/lang/pt.js",
     "public/i18n_locale_editor/wymeditor/lang/ru.js",
     "public/i18n_locale_editor/wymeditor/lang/sv.js",
     "public/i18n_locale_editor/wymeditor/lang/tr.js",
     "public/i18n_locale_editor/wymeditor/lang/zh_cn.js",
     "public/i18n_locale_editor/wymeditor/plugins/embed/jquery.wymeditor.embed.js",
     "public/i18n_locale_editor/wymeditor/plugins/fullscreen/icon_fullscreen.gif",
     "public/i18n_locale_editor/wymeditor/plugins/fullscreen/jquery.wymeditor.fullscreen.js",
     "public/i18n_locale_editor/wymeditor/plugins/hovertools/jquery.wymeditor.hovertools.js",
     "public/i18n_locale_editor/wymeditor/plugins/resizable/jquery.wymeditor.resizable.js",
     "public/i18n_locale_editor/wymeditor/plugins/resizable/readme.txt",
     "public/i18n_locale_editor/wymeditor/plugins/tidy/README",
     "public/i18n_locale_editor/wymeditor/plugins/tidy/jquery.wymeditor.tidy.js",
     "public/i18n_locale_editor/wymeditor/plugins/tidy/tidy.php",
     "public/i18n_locale_editor/wymeditor/plugins/tidy/wand.png",
     "public/i18n_locale_editor/wymeditor/skins/compact/icons.png",
     "public/i18n_locale_editor/wymeditor/skins/compact/skin.css",
     "public/i18n_locale_editor/wymeditor/skins/compact/skin.js",
     "public/i18n_locale_editor/wymeditor/skins/default/icons.png",
     "public/i18n_locale_editor/wymeditor/skins/default/skin.css",
     "public/i18n_locale_editor/wymeditor/skins/default/skin.js",
     "public/i18n_locale_editor/wymeditor/skins/minimal/images/bg.header.gif",
     "public/i18n_locale_editor/wymeditor/skins/minimal/images/bg.selector.silver.gif",
     "public/i18n_locale_editor/wymeditor/skins/minimal/images/bg.wymeditor.png",
     "public/i18n_locale_editor/wymeditor/skins/minimal/images/icons.silver.gif",
     "public/i18n_locale_editor/wymeditor/skins/minimal/skin.css",
     "public/i18n_locale_editor/wymeditor/skins/minimal/skin.js",
     "public/i18n_locale_editor/wymeditor/skins/silver/COPYING",
     "public/i18n_locale_editor/wymeditor/skins/silver/README",
     "public/i18n_locale_editor/wymeditor/skins/silver/images/bg.header.gif",
     "public/i18n_locale_editor/wymeditor/skins/silver/images/bg.selector.silver.gif",
     "public/i18n_locale_editor/wymeditor/skins/silver/images/bg.wymeditor.png",
     "public/i18n_locale_editor/wymeditor/skins/silver/images/icons.silver.gif",
     "public/i18n_locale_editor/wymeditor/skins/silver/skin.css",
     "public/i18n_locale_editor/wymeditor/skins/silver/skin.js",
     "public/i18n_locale_editor/wymeditor/skins/twopanels/icons.png",
     "public/i18n_locale_editor/wymeditor/skins/twopanels/skin.css",
     "public/i18n_locale_editor/wymeditor/skins/twopanels/skin.js",
     "public/i18n_locale_editor/wymeditor/skins/wymeditor_icon.png",
     "rails/init.rb",
     "spec/i18n_locale_editor_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/n1k/i18n_locale_editor}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rails i18n locale editor}
  s.test_files = [
    "spec/i18n_locale_editor_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<ya2yaml>, [">= 0.26"])
      s.add_runtime_dependency(%q<rails>, [">= 2.3.0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<ya2yaml>, [">= 0.26"])
      s.add_dependency(%q<rails>, [">= 2.3.0"])
      s.add_dependency(%q<i18n>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<ya2yaml>, [">= 0.26"])
    s.add_dependency(%q<rails>, [">= 2.3.0"])
    s.add_dependency(%q<i18n>, [">= 0"])
  end
end

